"use client";

import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type FormEvent,
  type KeyboardEvent,
} from "react";
import { Send, RotateCcw } from "lucide-react";
import {
  CHAT_API_URL,
  ChatError,
  sendChat,
  type ChatMessage,
} from "@/lib/chat";
import { cn } from "@/lib/cn";
import { SectionHeader } from "./SectionHeader";

const WELCOME: ChatMessage = {
  role: "assistant",
  content:
    "Hi — I'm kordmodanlou.engine, Danial's portfolio assistant. Ask me about his projects, experience, or how to get in touch.",
};

const SUGGESTIONS: string[] = [
  "Tell me about DigiHuman.",
  "What's his VR firefighter work?",
  "How can I hire him?",
];

const MAX_INPUT_CHARS = 2000;

export function ChatSection() {
  const [messages, setMessages] = useState<ChatMessage[]>([WELCOME]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const scrollRef = useRef<HTMLDivElement | null>(null);
  const textareaRef = useRef<HTMLTextAreaElement | null>(null);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    el.scrollTo({ top: el.scrollHeight, behavior: "smooth" });
  }, [messages, isLoading]);

  const backendReady = useMemo(() => CHAT_API_URL.length > 0, []);

  const submit = useCallback(
    async (text: string) => {
      const trimmed = text.trim();
      if (!trimmed || isLoading) return;

      if (!backendReady) {
        setError(
          "Chat backend isn't wired up yet. Reach out via the Contact section below.",
        );
        return;
      }

      const next: ChatMessage[] = [
        ...messages,
        { role: "user", content: trimmed.slice(0, MAX_INPUT_CHARS) },
      ];
      setMessages(next);
      setInput("");
      setIsLoading(true);
      setError(null);

      try {
        const reply = await sendChat(next);
        setMessages((prev) => [
          ...prev,
          { role: "assistant", content: reply || "No response." },
        ]);
      } catch (err) {
        const msg =
          err instanceof ChatError
            ? err.message
            : err instanceof Error
              ? err.message
              : "Something went wrong.";
        setError(msg);
        setMessages((prev) => prev.slice(0, -1));
        setInput(trimmed);
      } finally {
        setIsLoading(false);
        textareaRef.current?.focus();
      }
    },
    [backendReady, isLoading, messages],
  );

  const onFormSubmit = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    void submit(input);
  };

  const onKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      void submit(input);
    }
  };

  const reset = () => {
    if (isLoading) return;
    setMessages([WELCOME]);
    setInput("");
    setError(null);
  };

  return (
    <section id="chat" className="scroll-mt-16 border-b border-rule">
      <div className="mx-auto max-w-[1240px] px-5 py-20">
        <SectionHeader
          fullWidth
          num="008"
          kicker="ask the engine"
          title="Talk to the portfolio AI."
          intro="A small chatbot grounded in Danial's bio and projects. Answers are generated by Gemini 3.1 Flash Lite via a Cloudflare Worker — the persona prompt lives server-side."
        >
          <div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-start">
            <div className="flex min-w-0 flex-col gap-4">
              <div
                ref={scrollRef}
                aria-live="polite"
                aria-label="Chat transcript"
                className="glass-inner relative h-[440px] overflow-y-auto border border-rule p-4 sm:p-5"
              >
                <ol className="flex flex-col gap-3">
                  {messages.map((m, i) => (
                    <li
                      key={i}
                      className={cn(
                        "flex w-full",
                        m.role === "user" ? "justify-end" : "justify-start",
                      )}
                    >
                      <MessageBubble message={m} />
                    </li>
                  ))}
                  {isLoading && (
                    <li className="flex justify-start">
                      <TypingBubble />
                    </li>
                  )}
                </ol>
              </div>

              {error && (
                <div
                  role="alert"
                  className="border border-err/40 bg-err/5 px-3 py-2 font-mono text-[12px] text-err"
                >
                  {error}
                </div>
              )}

              <form
                onSubmit={onFormSubmit}
                className="flex flex-col gap-3 sm:flex-row sm:items-end"
              >
                <label htmlFor="chat-input" className="sr-only">
                  Message
                </label>
                <textarea
                  id="chat-input"
                  ref={textareaRef}
                  value={input}
                  onChange={(e) => setInput(e.target.value)}
                  onKeyDown={onKeyDown}
                  placeholder={
                    backendReady
                      ? "Ask about a project, role, or skill…"
                      : "Chat backend not configured yet."
                  }
                  maxLength={MAX_INPUT_CHARS}
                  rows={2}
                  disabled={isLoading || !backendReady}
                  className="min-h-[64px] w-full resize-y border border-rule bg-bg/60 px-3 py-2.5 font-mono text-[13px] text-fg placeholder:text-fg-mute focus:border-accent/60 focus:outline-none focus:ring-1 focus:ring-accent/40 disabled:opacity-60"
                />
                <button
                  type="submit"
                  disabled={isLoading || !input.trim() || !backendReady}
                  className="group inline-flex shrink-0 items-center justify-center gap-2 border border-accent bg-accent/10 px-5 py-3 font-mono text-[12px] uppercase tracking-[0.18em] text-accent transition-colors hover:bg-accent hover:text-bg disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:bg-accent/10 disabled:hover:text-accent"
                >
                  {isLoading ? "sending" : "send"}
                  <Send className="h-4 w-4" />
                </button>
              </form>
            </div>

            <aside className="glass-inner flex flex-col gap-4 border border-rule p-5 lg:w-[260px]">
              <div>
                <div className="label mb-3">try asking</div>
                <ul className="flex flex-col gap-2">
                  {SUGGESTIONS.map((s) => (
                    <li key={s}>
                      <button
                        type="button"
                        disabled={isLoading || !backendReady}
                        onClick={() => void submit(s)}
                        className="w-full border border-rule px-3 py-2 text-left font-mono text-[12px] text-fg-dim transition-colors hover:border-accent/60 hover:text-accent disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:border-rule disabled:hover:text-fg-dim"
                      >
                        {s}
                      </button>
                    </li>
                  ))}
                </ul>
              </div>

              <div className="border-t border-rule pt-4">
                <button
                  type="button"
                  onClick={reset}
                  disabled={isLoading || messages.length <= 1}
                  className="inline-flex items-center gap-2 font-mono text-[11px] uppercase tracking-[0.16em] text-fg-mute transition-colors hover:text-accent disabled:cursor-not-allowed disabled:opacity-50 disabled:hover:text-fg-mute"
                >
                  <RotateCcw className="h-3 w-3" />
                  reset
                </button>
              </div>

              <p className="border-t border-rule pt-4 font-mono text-[10.5px] leading-relaxed text-fg-mute">
                Conversations are not stored. The model can be wrong — verify
                anything critical via the{" "}
                <a
                  href="#contact"
                  className="text-fg-dim underline decoration-rule-strong underline-offset-2 hover:text-accent hover:decoration-accent"
                >
                  Contact
                </a>{" "}
                section.
              </p>
            </aside>
          </div>
        </SectionHeader>
      </div>
    </section>
  );
}

function MessageBubble({ message }: { message: ChatMessage }) {
  const isUser = message.role === "user";
  return (
    <div
      className={cn(
        "max-w-[88%] border px-3 py-2 font-mono text-[13px] leading-relaxed whitespace-pre-wrap",
        isUser
          ? "border-accent/60 bg-accent/5 text-fg"
          : "border-rule-strong bg-bg-1/60 text-fg-dim",
      )}
    >
      <div
        className={cn(
          "mb-1 font-mono text-[10px] uppercase tracking-[0.18em]",
          isUser ? "text-accent/70" : "text-fg-mute",
        )}
      >
        {isUser ? "you" : "engine"}
      </div>
      <div className="text-fg">{message.content}</div>
    </div>
  );
}

function TypingBubble() {
  return (
    <div className="border border-rule-strong bg-bg-1/60 px-3 py-2">
      <div className="flex items-center gap-1">
        <span className="block h-1.5 w-1.5 animate-pulse bg-accent [animation-delay:0ms]" />
        <span className="block h-1.5 w-1.5 animate-pulse bg-accent [animation-delay:150ms]" />
        <span className="block h-1.5 w-1.5 animate-pulse bg-accent [animation-delay:300ms]" />
      </div>
    </div>
  );
}
